{% set version = '1.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tensr
  version: {{ version|replace("-", "_") }}

source:
  fn: tensr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tensr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tensr/tensr_{{ version }}.tar.gz
  sha256: dded318c4f4f1fbe66d229047bc23db2c8ec462f066bb87a45c83e77541ecbfc

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1004

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-assertthat

  run:
    - r-base
    - r-assertthat

test:
  commands:
    - $R -e "library('tensr')"           # [not win]
    - "\"%R%\" -e \"library('tensr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tensr
  license: GPL-3
  summary: A collection of functions for Kronecker structured covariance estimation and testing
    under the array normal model. For estimation, maximum likelihood and Bayesian equivariant
    estimation procedures are implemented. For testing, a likelihood ratio testing procedure
    is available. This package also contains additional functions for manipulating and
    decomposing tensor data sets. This work was partially supported by NSF grant DMS-1505136.
    Details of the methods are described in Gerard and Hoff (2015) <doi:10.1016/j.jmva.2015.01.020>
    and Gerard and Hoff (2016) <doi:10.1016/j.laa.2016.04.033>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
