appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: xyTI4hMOSVj6IRY3WlzIq0Er1J69IDWwaSNGHwK/LE5c6JrLrjKmpmJiTw8v24rj6+AFZ/SAFDJ0c8j51aCHXFQeYqvyNNlOwa95Qzxx1MCtLDMV0C6NuWZKiKCx0ajMbfxIgzd/On7yY5ypBRcBHv9qsTY5I4l8OMvo42HKTapJ8pRVTW+ZSAK3XRM/ntymqx2RWQjoSFUPZcenMrZaot26JRrHxAvF8ha9A4keVswL8CNQ78d9CJ/W6Kh/y/Qa364sIZhZUVwa7CQAppnbesbgSRj9CC6GxBDpnJzXgAJS02+w1OR/8Z1/vlaqKPkiG6vCggPjmwh2+moOROgeYwomFrA/QJOs8+QsbIghHWsEcgX4bpet2mFt6XO5QlILafONlntuq8lbZX7l+fAh0vjO9xZc4kYAiqpynWj6sY57Ej176gbASZQcZP4MidmmVvE4t03F47q2U+gV3yuME42RzjgtwEUC7VUVeBb9ofmsgoJqeetDO4cdB7U8L9Ja84mzpAML4qEIVKXD6HPET6pV0G5+qSS6bi0qektw3aBP1nzh/BfqsBkqIuB8biT68vf9Q5m7KpQLDAoRDvafQm+ic0Buz7JPqF66qVdWDaV/uNRZt7EiTTxTOVWIF46VJwKOb4VwI9qIvY85u6ftGTEV+Fq1Kg+mLN/tbPGfkvg=
