travis:
  secure:
    BINSTAR_TOKEN: yBn6Kuj0kEK2S7we90dB1nXuXr9Kzn3aTLRaO01PzpkwzZ+1FA76tOPOQs2IWtXQAFfeTQ6GJQopjqFJp2ehKtotDjd0f77uFog6tJr5ZF9wj5y1miUaEZIQi6ljDqC+hLWrvrU8twqJsmc1RgemDJ4uaQOMvCwTLu8ZdWFt9G80qimdt/H4jZOyaOOLHEZJweDhA689a6tDY9uYd/ltMEj/zOWyNzFuwM6gT64kSNW0HZRQtdUkAvKG+A9RlDU+kNc7BiJp03ibAy6QX2kV60lv22h9Gv7WgtptkLu3PJtr3vaiMobq6MxkBXkWqtg9Upjf8eNlkifDoAeERlZQrmmRTemNTyUSo0UvuCcUkHHg16wwG3EEx6+rZ8XufrEqs0wmH+l0G7SEFRFwZbqhjj1VWKfsVw3U+md9hN9cR9GVpdmwQzFO54/sYix+tp8JNBPI428fNbXztYw/TkPUTXh/8mbM9dIESlBTdcSDVTo8R99XNvScVmKcOELq1nfjsLOaGhLwhASWS3N/lAQu8q6N0IUZJ0px6okHDYJGbHyXxNYNGEFm7rbS4S/FReMHxl+FcSFzCi8WwG+v2uCR430rQFQ65YwAxuN+R4ioHBAYLM3euxPi16joIfb/pwnl0V2Ne71wbVGqUaOOp6wobLktt1BeOD82cD3UxAL3NfE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
